CREATE DATABASE databasename;
use databasename;
go
ALTER DATABASE databasename
MODIFY NAME = new_database_name;
go
BACKUP DATABASE databasename TO DISK = 'C:\\FILEDNAMEBACKUP.bak'
WITH INIT --THIS TELL SQL TO OVERWIRTE ANY EXISTING FILE IN THE SPECIFIED LOCATION
GO
RESTORE DATABASE databasename FROM DISK ='c:\\FILEDNMEBACKUP.bak'
WITH REPLACE;  --REPLACE ANY EXISTING COPY OF A DATABASE 
GO
--DIFFERENTIAL BACKUP
BACKUP DATABASE databasename 
TO DISK = 'C:\\FILEDNAMEBACKUP.BACK'
WITH DIFFERENTIAL , INIT;
GO
RESTORE DATABASE databasename FROM DISK ='C:\\CO.BAK'
WITH NORECOVERY -- FULL BACKUP
GO
RESTORE DATABASE databasename FROM DISK ='C:\\CO.BAK'
WITH RECOVERY -- DIFFERENTIAL BACKUP
GO


DROP DATABASE databasename;
go
