CREATE DATABASE DBBANK COLLATE Latin1_General_100_CI_AI_UTF8;

CREATE TABLE BKBRANCH(
BCODE INT IDENTITY(1,1) PRIMARY KEY,
BNAME VARCHAR(30) NOT NULL,
BCITY VARCHAR(30) NULL
);

CREATE TABLE CUSTOMER(
CCODE INT IDENTITY(1,1),
CNAME VARCHAR(30),
CADDRESS VARCHAR(30),
PRIMARY KEY(CCODE)
);

CREATE TABLE ACCOUNT(
ACNUMBER INT IDENTITY(1,1),
ABALANCE DOUBLE
);

CREATE TABLE SAVINGACCOUNT(
SACODE INT IDENTITY(1,1),
ACODE INT,
INTRATE INT,

FOREIGN KEY(ACODE) REFERENCES ACCOUNT(ACODE)
ON DELETE CASCADE
ON UPDATE CASCADE

);

CREATE TABLE CHECKINGACCOUNT(
CHCODE INT IDENTITY(1,1),
ACODE INT,
OVERDRAFT INT,
FOREIGN KEY(ACODE) REFERENCES ACCOUNT(ACODE)
ON DELETE CASCADE
ON UPDATE CASCADE

);

CREATE TABLE LOAN (
LCODE INT IDENTITY(1,1),
LAMOUNT DOUBLE,
CCODE INT,
CONSTRAINT FOREIGN KEY(CCODE) REFERENCES CUSTOMER(CCODE)
ON DELETE SET NULL
ON UPDADE CASCADE
);

CREATE TABLE PAYMENT(
PCODE INT IDENTITY(1,1),
PDATE DATE,
PAMOUNT DOUBLE,
LCODE INT,
CONSTRAINT FOREIGN KEY(LCODE) REFERENCES LOAN(LCODE)
ON DELETE CASCADE
ON UPDATE CASCADE
);


CREATE TABLE EMPLOYEE(
EMCODE INT IDENTITY(1,1),
EMNAME VARCHAR(30),
EMPHONE INT,
EMMANAGER INT,
FOREIGN KEY(EMMANAGER ) REFERENCES EMPLOYEE(EMCODE)
);

CREATE TABLE EMPDEPENDENT (
DCODE INT IDENTITY(1,1),
DNAME VARCHAR(30),
EMPCODE INT,
FOREIGN KEY(EMPCODE ) REFERENCES EMPLOYEE(EMCODE)
ON DELETE CASCADE
ON UPDATE CASCADE
);